### ISSUE TITLE
feature request: queue up videos

### ISSUE THREAD

**Issue by sammcj** [facefusion/facefusion#151] opened 2023-10-13 04:17 UTC
It would be awesome if you could queue up videos to process.

For example, say you need to replace multiple people in a target video, you might have to convert everyone in the video with a different face a number of times. It would be cool if you could queue this up so you can leave it processing.

**Comment by henryruhs** [comment] 2023-10-13 05:54
Duplicate of https://github.com/facefusion/facefusion/issues/132

**Closed by henryruhs** 2023-10-13 05:54 UTC
