### ISSUE TITLE
Vram does not release automatically

### ISSUE THREAD

**Issue by petercham** [facefusion/facefusion#119] opened 2023-09-20 10:23 UTC
After executing a fusion, Vram will not be automatically released, causing local SD and other programs to fail to run properly.

**Comment by petercham** [comment] 2023-09-20 10:26
<img width="959" alt="1695205605872" src="https://github.com/facefusion/facefusion/assets/3765653/7e4fd591-8025-4a85-b3ac-015d7ba920e7">

**Comment by henryruhs** [comment] 2023-09-20 11:52
Fixed via https://github.com/facefusion/facefusion/commit/38233e3d0f00556f99b60a897c9f2e6626381a1a

I hope the performance does not drop too bad as the face analyser has to be recreated between swapper and enhancer.
Please report your experience. Thanks

**Closed by henryruhs** 2023-09-20 11:52 UTC

**Comment by petercham** [comment] 2023-09-21 10:19
> Fixed via [38233e3](https://github.com/facefusion/facefusion/commit/38233e3d0f00556f99b60a897c9f2e6626381a1a) on next branch.
> 
> I cannot release the VRAM used be tensorflow but [e798f26](https://github.com/facefusion/facefusion/commit/e798f26c9d40584d7e7114b252101f8700486ba3) reduced it to 512 MB.
> 
> I hope the performance does not drop too bad as the face analyser has to be recreated between swapper and enhancer. Please report your experience. Thanks

Started SD, started Facefusion, didn't run any inference tasks, Vram took up 17.2gb.

<img width="959" alt="1b309dbb78b13f61370d94f11b9059b" src="https://github.com/facefusion/facefusion/assets/3765653/7fb668c1-fbc0-40e4-848b-f4c3b38fb78a">

Facefusion automatically ran the preview, SD didn't perform the task, Vram took up 19.1gb.

<img width="959" alt="77a13fd480550d4a57474d0dc7d68e6" src="https://github.com/facefusion/facefusion/assets/3765653/bc405bdc-8457-4029-9cd7-b71764c261c3">

**Comment by petercham** [comment] 2023-09-21 10:21
Facefusiong performs one task, SD does not perform a task, and Vram's occupancy rises to 22.2gb during execution, before dropping back to 19.1gb.

<img width="959" alt="2d2c0eca2e2cc99cfa3309ca730e6b9" src="https://github.com/facefusion/facefusion/assets/3765653/1a19d343-aa9c-44cc-9edf-bed6b4d19066">

Facefusiong replaces the source and performs the task again, SD does not perform the task, and the Vram occupancy rises to 22gb during execution, before dropping back to 19.1gb.

<img width="959" alt="d9175dd159a9c3b7961e31128824545" src="https://github.com/facefusion/facefusion/assets/3765653/d8519db9-2bb1-4061-a879-7d89d4e226ad">

**Comment by henryruhs** [comment] 2023-09-21 10:25
Sorry but your reports are not helpful... don't mix your measurements with other software - that is pointless

**Comment by petercham** [comment] 2023-09-21 10:32
Facefusiong does not exit, SD performs the same 2 tasks (576×768, Step=30, Batch=4), and the Vram occupancy rises to about 22gb during execution, and then drops back to 19.1gb.

<img width="959" alt="0f058cfa599ad82b70e46f7fdecd5cd" src="https://github.com/facefusion/facefusion/assets/3765653/0c69b9cd-db2d-4555-a33f-6a9395d3f23a">

The above test was repeated a number of times, and Vram's footprint was able to drop back to 19.1gb at the end of the task, regardless of whether you were running A1111 or Facefusion.

Thanks so much for responding so quickly to the update, this branch is a huge enhancement to the experience!

**Comment by petercham** [comment] 2023-09-21 10:34
Through the above tests, it has been verified that, although tensorflow's Vram usage cannot be cleaned up, Facefusion no longer gradually fills up Vram due to the task process, which also gives the possibility of coexistence of all inference services that require resident Vrams.

**Comment by henryruhs** [comment] 2023-09-21 10:39
It's still not a helpful information for me... 19.1gb should not be occupied after processing - I assume that is caused by SD and that is actual the problem: it's an assumption and I have no valid statement or testing

**Comment by petercham** [comment] 2023-09-21 10:46
> 这对我来说仍然不是一个有用的信息...处理后不应占用 19.1gb - 我假设这是由 SD 引起的，这实际上是问题所在：这是一个假设，我没有有效的陈述或测试
> 
> 我还询问了潜在的性能下降。

The 19.1gb footprint is due to having 4 StableDiffusion services turned on at the same time. This is not a problem, the main purpose of the test is to verify that Vram does not accumulate resource usage due to task execution. Next I'll write a set of scripts to do some batch testing to further verify reliability and stability.

**Comment by henryruhs** [comment] 2023-09-21 10:47
I repeat myself: do not test it together with SD... I do not care about that.

**Comment by petercham** [comment] 2023-09-21 10:48
What are you looking forward to testing? I will do my best to assist

> 我再说一遍：不要与SD一起测试...我不在乎这个。如果您不能仅提供有关FF的信息，我将锁定此问题，因为这无处可去，并且您忽略了我的陈述。

What are you looking forward to testing? I will do my best to assist

**Comment by petercham** [comment] 2023-09-21 10:50
I'm sorry, but since English is not my first language, I may not be able to understand exactly what you're trying to say through a translation program.

**Comment by petercham** [comment] 2023-09-21 11:17
I assume you are wondering if there is any performance degradation in this branch? Since the current version of FaceFusion doesn't print the duration of each task, I made my own test script to record it. But in order to ensure that the test samples are varied, randomized, and do not use the same source and target, the test script is implemented by SD generating a different target graph each time.

**Comment by henryruhs** [comment] 2023-09-21 11:29
Thanks for testing...
