### ISSUE TITLE
Batch Processing of Source/Target images (Suggestion) 

### ISSUE THREAD

**Issue by viik420** [facefusion/facefusion#201] opened 2023-11-19 19:23 UTC
---

**Just a suggestion for Batch Processing of Source/Target images**
 
Why?

- **Source Images:** 
    While I'm uncertain if the current system supports this, it might enhance face detection if multiple source images could be used simultaneously. Utilizing images from various angles could potentially improve facial recognition, especially during video processing when the subject might be looking sideways or in a different direction. This approach would ensure that facial data from all angles is available.

- **Target Images**
    As has been previously suggested, the ability to process batch images or entire folders simultaneously is a feature that would greatly enhance efficiency. This would eliminate the need to select images individually, saving considerable time and effort.

---

**Comment by henryruhs** [comment] 2023-11-19 21:53
Duplicate of https://github.com/facefusion/facefusion/issues/132

I do no plan to support multiple source faces for now. Sorry...

**Closed by henryruhs** 2023-11-19 21:53 UTC
