### ISSUE TITLE
set `share=True` in `launch()`  i set but

### ISSUE THREAD

**Issue by chuan19** [facefusion/facefusion#115] opened 2023-09-18 06:20 UTC
Traceback (most recent call last):
  File "/root/autodl-tmp/facefusion/run.py", line 6, in <module>
    core.run()
  File "/root/autodl-tmp/facefusion/facefusion/core.py", line 229, in run
    ui.launch(share=True)
TypeError: launch() got an unexpected keyword argument 'share'

**Comment by chuan19** [comment] 2023-09-18 06:20
Traceback (most recent call last):
  File "/root/autodl-tmp/facefusion/run.py", line 6, in <module>
    core.run()
  File "/root/autodl-tmp/facefusion/facefusion/core.py", line 229, in run
    ui.launch(share=True)
TypeError: launch() got an unexpected keyword argument 'share'

**Comment by henryruhs** [comment] 2023-09-18 06:51
Duplicate of  https://github.com/facefusion/facefusion/issues/104

**Closed by henryruhs** 2023-09-18 06:51 UTC
