### ISSUE TITLE
Validating hash for open_nsfw failed

### ISSUE THREAD

**Issue by tutuaio** [facefusion/facefusion#766] opened 2024-09-25 09:42 UTC
~/facefusion$ python facefusion.py run
[FACEFUSION.DOWNLOAD] Validating hash for open_nsfw failed

how to fix this ? thanks.

**Comment by henryruhs** [comment] 2024-09-25 09:43
Duplicate of https://github.com/facefusion/facefusion/issues/765

**Closed by henryruhs** 2024-09-25 09:43 UTC
